<?php
return array (
  'xm_js' => 
  array (
    'fieldid' => '113',
    'modelid' => '1',
    'siteid' => '1',
    'field' => 'xm_js',
    'name' => '项目介绍',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'editor',
    'setting' => 'array (
  \'toolbar\' => \'full\',
  \'defaultvalue\' => \'\',
  \'enablekeylink\' => \'0\',
  \'replacenum\' => \'1\',
  \'link_mode\' => \'0\',
  \'enablesaveimage\' => \'0\',
  \'height\' => \'120\',
  \'disabled_page\' => \'1\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '1',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '1',
    'toolbar' => 'full',
    'defaultvalue' => '',
    'enablekeylink' => '0',
    'replacenum' => '1',
    'link_mode' => '0',
    'enablesaveimage' => '0',
    'height' => '120',
    'disabled_page' => '1',
  ),
  'xm_syrq' => 
  array (
    'fieldid' => '114',
    'modelid' => '1',
    'siteid' => '1',
    'field' => 'xm_syrq',
    'name' => '适用人群',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'editor',
    'setting' => 'array (
  \'toolbar\' => \'full\',
  \'defaultvalue\' => \'\',
  \'enablekeylink\' => \'0\',
  \'replacenum\' => \'1\',
  \'link_mode\' => \'0\',
  \'enablesaveimage\' => \'0\',
  \'height\' => \'120\',
  \'disabled_page\' => \'1\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '1',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '1',
    'toolbar' => 'full',
    'defaultvalue' => '',
    'enablekeylink' => '0',
    'replacenum' => '1',
    'link_mode' => '0',
    'enablesaveimage' => '0',
    'height' => '120',
    'disabled_page' => '1',
  ),
  'xm_sqzb' => 
  array (
    'fieldid' => '116',
    'modelid' => '1',
    'siteid' => '1',
    'field' => 'xm_sqzb',
    'name' => '术前准备',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'editor',
    'setting' => 'array (
  \'toolbar\' => \'full\',
  \'defaultvalue\' => \'\',
  \'enablekeylink\' => \'0\',
  \'replacenum\' => \'1\',
  \'link_mode\' => \'0\',
  \'enablesaveimage\' => \'0\',
  \'height\' => \'120\',
  \'disabled_page\' => \'1\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '1',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '1',
    'toolbar' => 'full',
    'defaultvalue' => '',
    'enablekeylink' => '0',
    'replacenum' => '1',
    'link_mode' => '0',
    'enablesaveimage' => '0',
    'height' => '120',
    'disabled_page' => '1',
  ),
  'xm_ssfs' => 
  array (
    'fieldid' => '117',
    'modelid' => '1',
    'siteid' => '1',
    'field' => 'xm_ssfs',
    'name' => '手术方式',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'editor',
    'setting' => 'array (
  \'toolbar\' => \'full\',
  \'defaultvalue\' => \'\',
  \'enablekeylink\' => \'0\',
  \'replacenum\' => \'1\',
  \'link_mode\' => \'0\',
  \'enablesaveimage\' => \'0\',
  \'height\' => \'120\',
  \'disabled_page\' => \'1\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '1',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '1',
    'toolbar' => 'full',
    'defaultvalue' => '',
    'enablekeylink' => '0',
    'replacenum' => '1',
    'link_mode' => '0',
    'enablesaveimage' => '0',
    'height' => '120',
    'disabled_page' => '1',
  ),
  'xm_byys' => 
  array (
    'fieldid' => '118',
    'modelid' => '1',
    'siteid' => '1',
    'field' => 'xm_byys',
    'name' => '本院优势',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'editor',
    'setting' => 'array (
  \'toolbar\' => \'full\',
  \'defaultvalue\' => \'\',
  \'enablekeylink\' => \'0\',
  \'replacenum\' => \'1\',
  \'link_mode\' => \'0\',
  \'enablesaveimage\' => \'0\',
  \'height\' => \'120\',
  \'disabled_page\' => \'1\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '1',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '1',
    'toolbar' => 'full',
    'defaultvalue' => '',
    'enablekeylink' => '0',
    'replacenum' => '1',
    'link_mode' => '0',
    'enablesaveimage' => '0',
    'height' => '120',
    'disabled_page' => '1',
  ),
  'xm_hfsj' => 
  array (
    'fieldid' => '119',
    'modelid' => '1',
    'siteid' => '1',
    'field' => 'xm_hfsj',
    'name' => '恢复时间',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'editor',
    'setting' => 'array (
  \'toolbar\' => \'full\',
  \'defaultvalue\' => \'\',
  \'enablekeylink\' => \'0\',
  \'replacenum\' => \'1\',
  \'link_mode\' => \'0\',
  \'enablesaveimage\' => \'0\',
  \'height\' => \'120\',
  \'disabled_page\' => \'1\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '1',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '1',
    'toolbar' => 'full',
    'defaultvalue' => '',
    'enablekeylink' => '0',
    'replacenum' => '1',
    'link_mode' => '0',
    'enablesaveimage' => '0',
    'height' => '120',
    'disabled_page' => '1',
  ),
  'xm_shhl' => 
  array (
    'fieldid' => '120',
    'modelid' => '1',
    'siteid' => '1',
    'field' => 'xm_shhl',
    'name' => '术后护理',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'editor',
    'setting' => 'array (
  \'toolbar\' => \'full\',
  \'defaultvalue\' => \'\',
  \'enablekeylink\' => \'0\',
  \'replacenum\' => \'1\',
  \'link_mode\' => \'0\',
  \'enablesaveimage\' => \'0\',
  \'height\' => \'120\',
  \'disabled_page\' => \'1\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '1',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '1',
    'toolbar' => 'full',
    'defaultvalue' => '',
    'enablekeylink' => '0',
    'replacenum' => '1',
    'link_mode' => '0',
    'enablesaveimage' => '0',
    'height' => '120',
    'disabled_page' => '1',
  ),
  'zj_zyzc' => 
  array (
    'fieldid' => '146',
    'modelid' => '1',
    'siteid' => '1',
    'field' => 'zj_zyzc',
    'name' => '主要职称',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'50\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '1',
    'isposition' => '1',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '1',
    'size' => '50',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'zj_xxzc' => 
  array (
    'fieldid' => '147',
    'modelid' => '1',
    'siteid' => '1',
    'field' => 'zj_xxzc',
    'name' => '详细职称',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'textarea',
    'setting' => 'array (
  \'width\' => \'95\',
  \'height\' => \'46\',
  \'defaultvalue\' => \'\',
  \'enablehtml\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '1',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '1',
    'width' => '95',
    'height' => '46',
    'defaultvalue' => '',
    'enablehtml' => '0',
  ),
  'zj_scxm' => 
  array (
    'fieldid' => '148',
    'modelid' => '1',
    'siteid' => '1',
    'field' => 'zj_scxm',
    'name' => '擅长项目',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'textarea',
    'setting' => 'array (
  \'width\' => \'95\',
  \'height\' => \'46\',
  \'defaultvalue\' => \'\',
  \'enablehtml\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '1',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '1',
    'width' => '95',
    'height' => '46',
    'defaultvalue' => '',
    'enablehtml' => '0',
  ),
  'xm_dbal' => 
  array (
    'fieldid' => '157',
    'modelid' => '1',
    'siteid' => '1',
    'field' => 'xm_dbal',
    'name' => '对比案例',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'30\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '1',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '1',
    'size' => '30',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'xm_yzzj' => 
  array (
    'fieldid' => '158',
    'modelid' => '1',
    'siteid' => '1',
    'field' => 'xm_yzzj',
    'name' => '医治专家',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'30\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '1',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '1',
    'size' => '30',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'catid' => 
  array (
    'fieldid' => '1',
    'modelid' => '1',
    'siteid' => '1',
    'field' => 'catid',
    'name' => '栏目',
    'tips' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '6',
    'pattern' => '/^[0-9]{1,6}$/',
    'errortips' => '请选择栏目',
    'formtype' => 'catid',
    'setting' => 'array (
  \'defaultvalue\' => \'\',
)',
    'formattribute' => '',
    'unsetgroupids' => '-99',
    'unsetroleids' => '-99',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '1',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '1',
    'disabled' => '0',
    'isomnipotent' => '0',
    'defaultvalue' => '',
  ),
  'title' => 
  array (
    'fieldid' => '3',
    'modelid' => '1',
    'siteid' => '1',
    'field' => 'title',
    'name' => '标题',
    'tips' => '',
    'css' => 'inputtitle',
    'minlength' => '1',
    'maxlength' => '80',
    'pattern' => '',
    'errortips' => '请输入标题',
    'formtype' => 'title',
    'setting' => '',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '1',
    'isadd' => '1',
    'isfulltext' => '1',
    'isposition' => '1',
    'listorder' => '4',
    'disabled' => '0',
    'isomnipotent' => '0',
  ),
  'keywords' => 
  array (
    'fieldid' => '5',
    'modelid' => '1',
    'siteid' => '1',
    'field' => 'keywords',
    'name' => '关键词',
    'tips' => '多关键词之间用空格或者“,”隔开',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '255',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'keyword',
    'setting' => '',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '1',
    'isadd' => '1',
    'isfulltext' => '1',
    'isposition' => '0',
    'listorder' => '7',
    'disabled' => '0',
    'isomnipotent' => '0',
  ),
  'copyfrom' => 
  array (
    'fieldid' => '21',
    'modelid' => '1',
    'siteid' => '1',
    'field' => 'copyfrom',
    'name' => '来源',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '100',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'copyfrom',
    'setting' => 'array (
  \'defaultvalue\' => \'\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '8',
    'disabled' => '0',
    'isomnipotent' => '0',
    'defaultvalue' => '',
  ),
  'author' => 
  array (
    'fieldid' => '108',
    'modelid' => '1',
    'siteid' => '1',
    'field' => 'author',
    'name' => '作者',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'author',
    'setting' => 'array (
  \'defaultvalue\' => \'\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '9',
    'disabled' => '0',
    'isomnipotent' => '0',
    'defaultvalue' => '',
  ),
  'description' => 
  array (
    'fieldid' => '6',
    'modelid' => '1',
    'siteid' => '1',
    'field' => 'description',
    'name' => '摘要',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '450',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'textarea',
    'setting' => 'array (
  \'width\' => \'98\',
  \'height\' => \'46\',
  \'defaultvalue\' => \'\',
  \'enablehtml\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '1',
    'isposition' => '1',
    'listorder' => '10',
    'disabled' => '0',
    'isomnipotent' => '0',
    'width' => '98',
    'height' => '46',
    'defaultvalue' => '',
    'enablehtml' => '0',
  ),
  'xm' => 
  array (
    'fieldid' => '123',
    'modelid' => '1',
    'siteid' => '1',
    'field' => 'xm',
    'name' => '<font color=#FF0000>项目说明</font',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 'array (
  \'options\' => \'是|1
否|0\',
  \'boxtype\' => \'radio\',
  \'fieldtype\' => \'varchar\',
  \'minnumber\' => \'1\',
  \'width\' => \'\',
  \'size\' => \'1\',
  \'defaultvalue\' => \'0\',
  \'outputtype\' => \'1\',
  \'filtertype\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '10',
    'disabled' => '0',
    'isomnipotent' => '0',
    'options' => '是|1
否|0',
    'boxtype' => 'radio',
    'fieldtype' => 'varchar',
    'minnumber' => '1',
    'width' => '',
    'size' => '1',
    'defaultvalue' => '0',
    'outputtype' => '1',
    'filtertype' => '0',
  ),
  'xm_info' => 
  array (
    'fieldid' => '115',
    'modelid' => '1',
    'siteid' => '1',
    'field' => 'xm_info',
    'name' => '<font color=#FF0000>项目详情</font',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'omnipotent',
    'setting' => 'array (
  \'formtext\' => \'<script type="text/javascript">
function showxm(){
	document.getElementById("sl_xm").style.display = "block";
}
function hidexm(){
	document.getElementById("sl_xm").style.display = "none";
}
</script>
<input type="radio" name="info[sl_xm]" value="yes" onclick="showxm()" />显示
<input type="radio" name="info[sl_xm]" value="no" checked onclick="hidexm()" />不显示
<div id="sl_xm" style="display:none">
<table width="98%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td colspan="2">项目介绍：<br>{xm_js}</td>
  </tr>
  <tr>
    <td colspan="2"><br>适用人群：<br>{xm_syrq}</td>
  </tr>
  <tr>
    <td colspan="2"><br>术前准备：<br>{xm_sqzb}</td>
  </tr>
  <tr>
    <td colspan="2"><br>医美方式：<br>{xm_ssfs}</td>
  </tr>
  <tr>
    <td colspan="2"><br>本院优势：<br>{xm_byys}</td>
  </tr>
  <tr>
    <td colspan="2"><br>恢复时间：<br>{xm_hfsj}</td>
  </tr>
  <tr>
    <td colspan="2"><br>术后护理：<br>{xm_shhl}</td>
  </tr>
  <tr>
    <td><br>对比案例：<br>{xm_dbal}</td>
    <td><br>医治专家：<br>{xm_yzzj}</td>
  </tr>
</table>
</div>\',
  \'fieldtype\' => \'varchar\',
  \'minnumber\' => \'1\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '11',
    'disabled' => '0',
    'isomnipotent' => '0',
    'formtext' => '<script type="text/javascript">
function showxm(){
	document.getElementById("sl_xm").style.display = "block";
}
function hidexm(){
	document.getElementById("sl_xm").style.display = "none";
}
</script>
<input type="radio" name="info[sl_xm]" value="yes" onclick="showxm()" />显示
<input type="radio" name="info[sl_xm]" value="no" checked onclick="hidexm()" />不显示
<div id="sl_xm" style="display:none">
<table width="98%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td colspan="2">项目介绍：<br>{xm_js}</td>
  </tr>
  <tr>
    <td colspan="2"><br>适用人群：<br>{xm_syrq}</td>
  </tr>
  <tr>
    <td colspan="2"><br>术前准备：<br>{xm_sqzb}</td>
  </tr>
  <tr>
    <td colspan="2"><br>医美方式：<br>{xm_ssfs}</td>
  </tr>
  <tr>
    <td colspan="2"><br>本院优势：<br>{xm_byys}</td>
  </tr>
  <tr>
    <td colspan="2"><br>恢复时间：<br>{xm_hfsj}</td>
  </tr>
  <tr>
    <td colspan="2"><br>术后护理：<br>{xm_shhl}</td>
  </tr>
  <tr>
    <td><br>对比案例：<br>{xm_dbal}</td>
    <td><br>医治专家：<br>{xm_yzzj}</td>
  </tr>
</table>
</div>',
    'fieldtype' => 'varchar',
    'minnumber' => '1',
  ),
  'updatetime' => 
  array (
    'fieldid' => '7',
    'modelid' => '1',
    'siteid' => '1',
    'field' => 'updatetime',
    'name' => '更新时间',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'datetime',
    'setting' => 'array (
  \'dateformat\' => \'int\',
  \'format\' => \'Y-m-d H:i:s\',
  \'defaulttype\' => \'1\',
  \'defaultvalue\' => \'\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '1',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '12',
    'disabled' => '0',
    'isomnipotent' => '0',
    'dateformat' => 'int',
    'format' => 'Y-m-d H:i:s',
    'defaulttype' => '1',
    'defaultvalue' => '',
  ),
  'content' => 
  array (
    'fieldid' => '8',
    'modelid' => '1',
    'siteid' => '1',
    'field' => 'content',
    'name' => '内容',
    'tips' => '<div class="content_attr"><label><input name="add_introduce" type="checkbox"  value="1" checked>是否截取内容</label><input type="text" name="introcude_length" value="350" size="3">字符至内容摘要
<label><input type=\'checkbox\' name=\'auto_thumb\' value="1" checked>是否获取内容第</label><input type="text" name="auto_thumb_no" value="1" size="2" class="">张图片作为标题图片
</div>',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '999999',
    'pattern' => '',
    'errortips' => '内容不能为空',
    'formtype' => 'editor',
    'setting' => 'array (
  \'toolbar\' => \'full\',
  \'defaultvalue\' => \'\',
  \'enablekeylink\' => \'1\',
  \'replacenum\' => \'2\',
  \'link_mode\' => \'0\',
  \'enablesaveimage\' => \'1\',
  \'height\' => \'\',
  \'disabled_page\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '1',
    'isposition' => '0',
    'listorder' => '13',
    'disabled' => '0',
    'isomnipotent' => '0',
    'toolbar' => 'full',
    'defaultvalue' => '',
    'enablekeylink' => '1',
    'replacenum' => '2',
    'link_mode' => '0',
    'enablesaveimage' => '1',
    'height' => '',
    'disabled_page' => '0',
  ),
  'video_url' => 
  array (
    'fieldid' => '145',
    'modelid' => '1',
    'siteid' => '1',
    'field' => 'video_url',
    'name' => '视频地址',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'downfiles',
    'setting' => 'array (
  \'upload_allowext\' => \'flv|mp4\',
  \'isselectfile\' => \'1\',
  \'isselectimage\' => \'0\',
  \'upload_number\' => \'1\',
  \'downloadlink\' => \'0\',
  \'downloadtype\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '13',
    'disabled' => '0',
    'isomnipotent' => '0',
    'upload_allowext' => 'flv|mp4',
    'isselectfile' => '1',
    'isselectimage' => '0',
    'upload_number' => '1',
    'downloadlink' => '0',
    'downloadtype' => '0',
  ),
  'thumb' => 
  array (
    'fieldid' => '4',
    'modelid' => '1',
    'siteid' => '1',
    'field' => 'thumb',
    'name' => '缩略图',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '100',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'image',
    'setting' => 'array (
  \'size\' => \'50\',
  \'defaultvalue\' => \'\',
  \'show_type\' => \'1\',
  \'upload_maxsize\' => \'1024\',
  \'upload_allowext\' => \'jpg|jpeg|gif|png|bmp\',
  \'watermark\' => \'0\',
  \'isselectimage\' => \'1\',
  \'images_width\' => \'\',
  \'images_height\' => \'\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '1',
    'listorder' => '14',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '50',
    'defaultvalue' => '',
    'show_type' => '1',
    'upload_maxsize' => '1024',
    'upload_allowext' => 'jpg|jpeg|gif|png|bmp',
    'watermark' => '0',
    'isselectimage' => '1',
    'images_width' => '',
    'images_height' => '',
  ),
  'relation' => 
  array (
    'fieldid' => '19',
    'modelid' => '1',
    'siteid' => '1',
    'field' => 'relation',
    'name' => '相关文章',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'omnipotent',
    'setting' => 'array (
  \'formtext\' => \'<input type=\\\'hidden\\\' name=\\\'info[relation]\\\' id=\\\'relation\\\' value=\\\'{FIELD_VALUE}\\\' style=\\\'50\\\' >
<ul class="list-dot" id="relation_text"></ul>
<div>
<input type=\\\'button\\\' value="添加相关" onclick="omnipotent(\\\'selectid\\\',\\\'?m=content&c=content&a=public_relationlist&modelid={MODELID}\\\',\\\'添加相关文章\\\',1)" class="button" style="width:66px;">
<span class="edit_content">
<input type=\\\'button\\\' value="显示已有" onclick="show_relation({MODELID},{ID})" class="button" style="width:66px;">
</span>
</div>\',
  \'fieldtype\' => \'varchar\',
  \'minnumber\' => \'1\',
)',
    'formattribute' => '',
    'unsetgroupids' => '2,6,4,5,1,7',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '1',
    'isposition' => '0',
    'listorder' => '15',
    'disabled' => '0',
    'isomnipotent' => '0',
    'formtext' => '<input type=\'hidden\' name=\'info[relation]\' id=\'relation\' value=\'{FIELD_VALUE}\' style=\'50\' >
<ul class="list-dot" id="relation_text"></ul>
<div>
<input type=\'button\' value="添加相关" onclick="omnipotent(\'selectid\',\'?m=content&c=content&a=public_relationlist&modelid={MODELID}\',\'添加相关文章\',1)" class="button" style="width:66px;">
<span class="edit_content">
<input type=\'button\' value="显示已有" onclick="show_relation({MODELID},{ID})" class="button" style="width:66px;">
</span>
</div>',
    'fieldtype' => 'varchar',
    'minnumber' => '1',
  ),
  'pages' => 
  array (
    'fieldid' => '10',
    'modelid' => '1',
    'siteid' => '1',
    'field' => 'pages',
    'name' => '分页方式',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'pages',
    'setting' => '',
    'formattribute' => '',
    'unsetgroupids' => '-99',
    'unsetroleids' => '-99',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '16',
    'disabled' => '0',
    'isomnipotent' => '0',
  ),
  'inputtime' => 
  array (
    'fieldid' => '11',
    'modelid' => '1',
    'siteid' => '1',
    'field' => 'inputtime',
    'name' => '发布时间',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'datetime',
    'setting' => 'array (
  \'fieldtype\' => \'int\',
  \'format\' => \'Y-m-d H:i:s\',
  \'defaulttype\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '1',
    'listorder' => '17',
    'disabled' => '0',
    'isomnipotent' => '0',
    'fieldtype' => 'int',
    'format' => 'Y-m-d H:i:s',
    'defaulttype' => '0',
  ),
  'posids' => 
  array (
    'fieldid' => '12',
    'modelid' => '1',
    'siteid' => '1',
    'field' => 'posids',
    'name' => '推荐位',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'posid',
    'setting' => 'array (
  \'cols\' => \'4\',
  \'width\' => \'125\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '18',
    'disabled' => '0',
    'isomnipotent' => '0',
    'cols' => '4',
    'width' => '125',
  ),
  'zjxx' => 
  array (
    'fieldid' => '149',
    'modelid' => '1',
    'siteid' => '1',
    'field' => 'zjxx',
    'name' => '<font color=#A900FF>专家信息</font',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'omnipotent',
    'setting' => 'array (
  \'formtext\' => \'<script type="text/javascript">
function showzj(){
	document.getElementById("sl_zj").style.display = "block";
}
function hidezj(){
	document.getElementById("sl_zj").style.display = "none";
}
</script>
<input type="radio" name="info[sl_zj]" value="yes" onclick="showzj()" />显示
<input type="radio" name="info[sl_zj]" value="no" checked onclick="hidezj()" />不显示
<div id="sl_zj" style="display:none">
<table width="98%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td>主要职称：<br>{zj_zyzc}</td>
  </tr>
  <tr>
    <td>详细职称：<br>{zj_xxzc}</td>
  </tr>
  <tr>
    <td>擅长项目：<br>{zj_scxm}</td>
  </tr>
</table>
</div>\',
  \'fieldtype\' => \'varchar\',
  \'minnumber\' => \'1\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '18',
    'disabled' => '0',
    'isomnipotent' => '0',
    'formtext' => '<script type="text/javascript">
function showzj(){
	document.getElementById("sl_zj").style.display = "block";
}
function hidezj(){
	document.getElementById("sl_zj").style.display = "none";
}
</script>
<input type="radio" name="info[sl_zj]" value="yes" onclick="showzj()" />显示
<input type="radio" name="info[sl_zj]" value="no" checked onclick="hidezj()" />不显示
<div id="sl_zj" style="display:none">
<table width="98%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td>主要职称：<br>{zj_zyzc}</td>
  </tr>
  <tr>
    <td>详细职称：<br>{zj_xxzc}</td>
  </tr>
  <tr>
    <td>擅长项目：<br>{zj_scxm}</td>
  </tr>
</table>
</div>',
    'fieldtype' => 'varchar',
    'minnumber' => '1',
  ),
  'al_info' => 
  array (
    'fieldid' => '159',
    'modelid' => '1',
    'siteid' => '1',
    'field' => 'al_info',
    'name' => '案例详情',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'omnipotent',
    'setting' => 'array (
  \'formtext\' => \'<script type="text/javascript">
function showal(){
	document.getElementById("sl_al").style.display = "block";
}
function hideal(){
	document.getElementById("sl_al").style.display = "none";
}
</script>
<input type="radio" name="info[sl_al]" value="yes" onclick="showal()" />显示
<input type="radio" name="info[sl_al]" value="no" checked onclick="hideal()" />不显示
<div id="sl_al" style="display:none">
<table width="98%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td><br>术前照片：<br>{shuqian}</td>
    <td><br>术后照片：<br>{shuhou}</td>
  </tr>
  <tr>
    <td colspan="2">顾客信息：<br>{guke}</td>
  </tr>
  <tr>
    <td colspan="2"><br>手术项目：<br>{xiangmu}</td>
  </tr>
  <tr>
    <td colspan="2"><br>打造专家：<br>{zhuanjia}</td>
  </tr>
</table>
</div>\',
  \'fieldtype\' => \'varchar\',
  \'minnumber\' => \'1\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '20',
    'disabled' => '0',
    'isomnipotent' => '0',
    'formtext' => '<script type="text/javascript">
function showal(){
	document.getElementById("sl_al").style.display = "block";
}
function hideal(){
	document.getElementById("sl_al").style.display = "none";
}
</script>
<input type="radio" name="info[sl_al]" value="yes" onclick="showal()" />显示
<input type="radio" name="info[sl_al]" value="no" checked onclick="hideal()" />不显示
<div id="sl_al" style="display:none">
<table width="98%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td><br>术前照片：<br>{shuqian}</td>
    <td><br>术后照片：<br>{shuhou}</td>
  </tr>
  <tr>
    <td colspan="2">顾客信息：<br>{guke}</td>
  </tr>
  <tr>
    <td colspan="2"><br>手术项目：<br>{xiangmu}</td>
  </tr>
  <tr>
    <td colspan="2"><br>打造专家：<br>{zhuanjia}</td>
  </tr>
</table>
</div>',
    'fieldtype' => 'varchar',
    'minnumber' => '1',
  ),
  'islink' => 
  array (
    'fieldid' => '73',
    'modelid' => '1',
    'siteid' => '1',
    'field' => 'islink',
    'name' => '转向链接',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'islink',
    'setting' => '',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '30',
    'disabled' => '0',
    'isomnipotent' => '0',
  ),
  'url' => 
  array (
    'fieldid' => '13',
    'modelid' => '1',
    'siteid' => '1',
    'field' => 'url',
    'name' => 'URL',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '100',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => '',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '1',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '50',
    'disabled' => '0',
    'isomnipotent' => '0',
  ),
  'listorder' => 
  array (
    'fieldid' => '14',
    'modelid' => '1',
    'siteid' => '1',
    'field' => 'listorder',
    'name' => '排序',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '6',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'number',
    'setting' => '',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '1',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '51',
    'disabled' => '0',
    'isomnipotent' => '0',
  ),
  'template' => 
  array (
    'fieldid' => '16',
    'modelid' => '1',
    'siteid' => '1',
    'field' => 'template',
    'name' => '内容页模板',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '30',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'template',
    'setting' => 'array (
  \'size\' => \'\',
  \'defaultvalue\' => \'\',
)',
    'formattribute' => '',
    'unsetgroupids' => '-99',
    'unsetroleids' => '-99',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '53',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '',
    'defaultvalue' => '',
  ),
  'status' => 
  array (
    'fieldid' => '15',
    'modelid' => '1',
    'siteid' => '1',
    'field' => 'status',
    'name' => '状态',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '2',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => '',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '1',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '55',
    'disabled' => '0',
    'isomnipotent' => '0',
  ),
  'username' => 
  array (
    'fieldid' => '80',
    'modelid' => '1',
    'siteid' => '1',
    'field' => 'username',
    'name' => '用户名',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '20',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => '',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '1',
    'issystem' => '1',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '98',
    'disabled' => '0',
    'isomnipotent' => '0',
  ),
  'shuqian' => 
  array (
    'fieldid' => '109',
    'modelid' => '1',
    'siteid' => '1',
    'field' => 'shuqian',
    'name' => '[案例]术前照片',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'image',
    'setting' => 'array (
  \'size\' => \'\',
  \'defaultvalue\' => \'\',
  \'show_type\' => \'1\',
  \'upload_maxsize\' => \'\',
  \'upload_allowext\' => \'gif|jpg|jpeg|png|bmp\',
  \'watermark\' => \'0\',
  \'isselectimage\' => \'1\',
  \'images_width\' => \'\',
  \'images_height\' => \'\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '101',
    'disabled' => '0',
    'isomnipotent' => '1',
    'size' => '',
    'defaultvalue' => '',
    'show_type' => '1',
    'upload_maxsize' => '',
    'upload_allowext' => 'gif|jpg|jpeg|png|bmp',
    'watermark' => '0',
    'isselectimage' => '1',
    'images_width' => '',
    'images_height' => '',
  ),
  'shuhou' => 
  array (
    'fieldid' => '110',
    'modelid' => '1',
    'siteid' => '1',
    'field' => 'shuhou',
    'name' => '[案例]术后照片',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'image',
    'setting' => 'array (
  \'size\' => \'\',
  \'defaultvalue\' => \'\',
  \'show_type\' => \'1\',
  \'upload_maxsize\' => \'\',
  \'upload_allowext\' => \'gif|jpg|jpeg|png|bmp\',
  \'watermark\' => \'0\',
  \'isselectimage\' => \'1\',
  \'images_width\' => \'\',
  \'images_height\' => \'\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '102',
    'disabled' => '0',
    'isomnipotent' => '1',
    'size' => '',
    'defaultvalue' => '',
    'show_type' => '1',
    'upload_maxsize' => '',
    'upload_allowext' => 'gif|jpg|jpeg|png|bmp',
    'watermark' => '0',
    'isselectimage' => '1',
    'images_width' => '',
    'images_height' => '',
  ),
  'guke' => 
  array (
    'fieldid' => '111',
    'modelid' => '1',
    'siteid' => '1',
    'field' => 'guke',
    'name' => '[案例]顾客信息',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'50\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '1',
    'isposition' => '0',
    'listorder' => '103',
    'disabled' => '0',
    'isomnipotent' => '1',
    'size' => '50',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'xiangmu' => 
  array (
    'fieldid' => '155',
    'modelid' => '1',
    'siteid' => '1',
    'field' => 'xiangmu',
    'name' => '[案例]手术项目',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'50\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '1',
    'isposition' => '0',
    'listorder' => '104',
    'disabled' => '0',
    'isomnipotent' => '1',
    'size' => '50',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'zhuanjia' => 
  array (
    'fieldid' => '156',
    'modelid' => '1',
    'siteid' => '1',
    'field' => 'zhuanjia',
    'name' => '[案例]打造专家',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'50\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '1',
    'isposition' => '0',
    'listorder' => '105',
    'disabled' => '0',
    'isomnipotent' => '1',
    'size' => '50',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
);
?>