/**
 *  右边固定浮动小导航条 by sam 2014年5月2日 15:53:03
 */
document.writeln("<style type=\"text/css\">");
document.writeln("    /* 右边固定浮动小导航条 S */");
document.writeln("    .mod-fixedBar01{width:131px;height:143px;position:fixed;top:258px;right:0px; z-index:888}");
document.writeln("    *html .mod-fixedBar01{margin-top:258px;position:absolute;top:expression(eval(document.documentElement.scrollTop));}");
document.writeln("    .mod-fixedBar01 li{width:131px;height:60px;}");
document.writeln("    .mod-fixedBar01 li img{float:right;}");
document.writeln("    .mod-fixedBar01 li a{height:49px;float:right;display:block;min-width:47px;max-width:131px;}");
document.writeln("    .mod-fixedBar01 li a .shows{display:block;}");
document.writeln("    .mod-fixedBar01 li a .hides{margin-right:-143px;cursor:pointer;cursor:hand;}");
document.writeln("    .mod-fixedBar01 li a.youhui .hides{display:none;position:absolute;right:190px;top:2px;}");
document.writeln("    .mod-fixedBar01 li a.wei2 .hides{display:none;position:absolute;right:190px;top:61px;}");
document.writeln("    /* 右边固定浮动小导航条 E */");
document.writeln("</style>");
document.writeln("");
document.writeln("<!-- 右边固定浮动小导航条 by sam 2014年5月2日 15:53:03 -->");
document.writeln("<div class=\"mod-fixedBar01\">");
document.writeln("	<ul>");
document.writeln("		<li>");
document.writeln("            <a href=\"javascript:swtUrl();\">");
document.writeln("                <img src=\"http://www.mebel.com.cn/images/mod-fixedBar01-ll01.png\" width=\"131\" height=\"49\" class=\"hides\">");
document.writeln("                <img src=\"http://www.mebel.com.cn/images/mod-fixedBar01-l01.png\" width=\"47\" height=\"49\" class=\"shows\">");
document.writeln("            </a>");
document.writeln("        </li>");
document.writeln("		<li>");
document.writeln("            <a href=\"javascript:swtUrl();\">");
document.writeln("                <img src=\"http://www.mebel.com.cn/images/mod-fixedBar01-ll03.png\" width=\"131\" height=\"49\" class=\"hides\">");
document.writeln("                <img src=\"http://www.mebel.com.cn/images/mod-fixedBar01-l03.png\" width=\"47\" height=\"49\" class=\"shows\">");
document.writeln("            </a>");
document.writeln("        </li>");
//document.writeln("		<li>");
//document.writeln("            <a class=\"youhui\">");
//document.writeln("                <img src=\"http://www.mebel.com.cn/images/mod-fixedBar01-l02.png\" width=\"47\" height=\"49\" class=\"shows\">");
//document.writeln("                <img src=\"http://www.mebel.com.cn/images/youhuileft3.png\" width=\"260\" height=\"500\" class=\"hides\" usemap=\"#taklhtml\" style=\"display: none;\">");
//document.writeln("                <map name=\"taklhtml\"><area shape=\"rect\" coords=\"26,273,115,300 \" href=\"javascript:swtUrl();\"></map>");
//document.writeln("            </a>");
//document.writeln("        </li>");
document.writeln("		<li>");
document.writeln("            <a class=\"wei2\">");
document.writeln("                <img src=\"http://www.mebel.com.cn/images/wxleft0.jpg\" width=\"47\" height=\"49\" class=\"shows\">");
document.writeln("                <img src=\"http://www.mebel.com.cn/images/wxxleft2.png\" width=\"135\" height=\"167\" class=\"hides\" usemap=\"#taklhtml\" style=\"display: none;\">");
document.writeln("                <map name=\"taklhtml\"><area shape=\"rect\" coords=\"26,273,115,300 \" href=\"javascript:swtUrl();\"></map>");
document.writeln("            </a>");
document.writeln("        </li>");
document.writeln("		<li>");
document.writeln("            <a href=\"javascript:swtUrl();\">");
document.writeln("                <img src=\"http://www.mebel.com.cn/images/mod-fixedBar01-ll04.png\" width=\"131\" height=\"49\" class=\"hides\">");
document.writeln("                <img src=\"http://www.mebel.com.cn/images/mod-fixedBar01-l04.png\" width=\"47\" height=\"49\" class=\"shows\">");
document.writeln("            </a>");
document.writeln("        </li>");
document.writeln("		<li>");
document.writeln("            <a href=\"javascript:swtUrl();\">");
document.writeln("                <img src=\"http://www.mebel.com.cn/images/mod-fixedBar01-ll05.png\" width=\"131\" height=\"49\" class=\"hides\">");
document.writeln("                <img src=\"http://www.mebel.com.cn/images/mod-fixedBar01-l05.png\" width=\"47\" height=\"49\" class=\"shows\">");
document.writeln("            </a>");
document.writeln("        </li>");
document.writeln("		<li>");
document.writeln("            <a id=\"top_btn\">");
document.writeln("                <img src=\"http://www.mebel.com.cn/images/mod-fixedBar01-ll06.png\" width=\"131\" height=\"49\" class=\"hides\">");
document.writeln("                <img src=\"http://www.mebel.com.cn/images/mod-fixedBar01-l06.png\" width=\"47\" height=\"49\" class=\"shows\">");
document.writeln("            </a>");
document.writeln("        </li>");
document.writeln("	</ul>");
document.writeln("</div>");
document.writeln("<script type=\"text/javascript\">");
document.writeln("$(document).ready(function(){");
document.writeln("");
document.writeln("	$(\".mod-fixedBar01 a\").hover(function(){");
document.writeln("		if($(this).prop(\"className\")==\"youhui\" || $(this).prop(\"className\")==\"wei2\"){");
document.writeln("			$(this).children(\"img.hides\").show();");
document.writeln("		}else{");
document.writeln("			$(this).children(\"img.hides\").show();");
document.writeln("			$(this).children(\"img.shows\").hide();");
document.writeln("			$(this).children(\"img.hides\").animate({marginRight:\'0px\'},\'slow\'); ");
document.writeln("		}");
document.writeln("	},function(){ ");
document.writeln("		if($(this).prop(\"className\")==\"youhui\" || $(this).prop(\"className\")==\"wei2\"){");
document.writeln("			$(this).children(\"img.hides\").hide(\'slow\');");
document.writeln("		}else{");
document.writeln("			$(this).children(\"img.hides\").animate({marginRight:\'-143px\'},\'slow\',function(){$(this).hide();$(this).next(\"img.shows\").show();});");
document.writeln("		}");
document.writeln("	});");
document.writeln("");
document.writeln("	$(\"#top_btn\").click(function(){if(scroll==\"off\") return;$(\"html,body\").animate({scrollTop: 0}, 600);});");
document.writeln("");
document.writeln("});");
document.writeln("</script>");
document.writeln("<!-- 右边固定浮动小导航条 by sam 2014年5月2日 15:53:03 -->");