<?php
return array (
  1 => 
  array (
    'posid' => '1',
    'modelid' => '0',
    'catid' => '0',
    'name' => '页头_最新消息',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  19 => 
  array (
    'posid' => '19',
    'modelid' => '1',
    'catid' => '13',
    'name' => '首页_推荐项目',
    'maxnum' => '20',
    'extention' => '{zt_tjxm}',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  18 => 
  array (
    'posid' => '18',
    'modelid' => '1',
    'catid' => '0',
    'name' => '首页_活动专区',
    'maxnum' => '20',
    'extention' => '{hd_area}',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  16 => 
  array (
    'posid' => '16',
    'modelid' => '1',
    'catid' => '33',
    'name' => '口腔专家',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  15 => 
  array (
    'posid' => '15',
    'modelid' => '1',
    'catid' => '33',
    'name' => '注射专家',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  14 => 
  array (
    'posid' => '14',
    'modelid' => '1',
    'catid' => '33',
    'name' => '皮肤专家',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  13 => 
  array (
    'posid' => '13',
    'modelid' => '1',
    'catid' => '33',
    'name' => '整形专家',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  12 => 
  array (
    'posid' => '12',
    'modelid' => '1',
    'catid' => '33',
    'name' => '专家_栏目推荐',
    'maxnum' => '4',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  11 => 
  array (
    'posid' => '11',
    'modelid' => '1',
    'catid' => '0',
    'name' => '边栏_资讯推荐',
    'maxnum' => '8',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  10 => 
  array (
    'posid' => '10',
    'modelid' => '0',
    'catid' => '0',
    'name' => '首页_特色项目',
    'maxnum' => '24',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  9 => 
  array (
    'posid' => '9',
    'modelid' => '0',
    'catid' => '13',
    'name' => '导航_口腔专题',
    'maxnum' => '2',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  8 => 
  array (
    'posid' => '8',
    'modelid' => '0',
    'catid' => '13',
    'name' => '导航_注射专题',
    'maxnum' => '2',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  7 => 
  array (
    'posid' => '7',
    'modelid' => '0',
    'catid' => '13',
    'name' => '导航_皮肤专题',
    'maxnum' => '2',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  6 => 
  array (
    'posid' => '6',
    'modelid' => '0',
    'catid' => '13',
    'name' => '导航_整形专题',
    'maxnum' => '2',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  5 => 
  array (
    'posid' => '5',
    'modelid' => '0',
    'catid' => '13',
    'name' => '导航_品牌专题',
    'maxnum' => '2',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  4 => 
  array (
    'posid' => '4',
    'modelid' => '0',
    'catid' => '33',
    'name' => '边栏_专家推荐',
    'maxnum' => '20',
    'extention' => '{zj_zyzc}',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  3 => 
  array (
    'posid' => '3',
    'modelid' => '0',
    'catid' => '0',
    'name' => '边栏_热点图片',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  2 => 
  array (
    'posid' => '2',
    'modelid' => '12',
    'catid' => '44',
    'name' => '首页_焦点图片',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  20 => 
  array (
    'posid' => '20',
    'modelid' => '1',
    'catid' => '0',
    'name' => '首页_特邀专家',
    'maxnum' => '20',
    'extention' => '{zj_tyzj}',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
);
?>